### ISSUE TITLE
Create a java program to find the number of consonants and vowels in a string.

### ISSUE THREAD

**Issue by arushitrivedi** [The-Arjun-Thakor/HacktoberFest-2023#12]
Hi @The-Arjun-Thakor! I realised there is no directory for java in the script folder. Can you please assign me to work on this issue under the tag of "**hacktoberfest**"?

**Comment by aqsa-isha** [comment]
hello
Assign me this issue

**Comment by The-Arjun-Thakor** [comment]
Users have to create the folder according to their code of language therefore no issues are there.😊
